# Generated by Django 3.1.6 on 2021-03-13 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 14, 4, 2, 151451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='Description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='Important',
            field=models.BooleanField(default=None),
        ),
    ]
