# Generated by Django 3.1.7 on 2021-03-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210313_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='Name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
