# Generated by Django 3.1.6 on 2021-05-15 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_todomodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='Name',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
